#!/bin/sh
set -e

if ! grep '^[[:space:]]*XMODIFIERS=[^#]*@im=' /etc/environment > /dev/null
then
	echo -n 'adding XMODIFIERS to /etc/environment ...'
	echo 'XMODIFIERS=@im=SCIM' >> /etc/environment
	echo ' done'
fi

if ! grep '^[[:space:]]*GTK_IM_MODULE=' /etc/environment > /dev/null
then
	echo -n 'adding GTK_IM_MODULE to /etc/environment ...'
	echo 'GTK_IM_MODULE=scim' >> /etc/environment
	echo ' done'
fi

if ! grep '^[[:space:]]*QT_IM_MODULE=' /etc/environment > /dev/null
then
	echo -n 'adding QT_IM_MODULE to /etc/environment ...'
	echo 'QT_IM_MODULE=scim' >> /etc/environment
	echo ' done'
fi

exit 0

