;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;;                                                                     ;;;
;;;                     Carnegie Mellon University                      ;;;
;;;                  and Alan W Black and Kevin Lenzo                   ;;;
;;;                      Copyright (c) 1998-2000                        ;;;
;;;                        All Rights Reserved.                         ;;;
;;;                                                                     ;;;
;;; Permission is hereby granted, free of charge, to use and distribute ;;;
;;; this software and its documentation without restriction, including  ;;;
;;; without limitation the rights to use, copy, modify, merge, publish, ;;;
;;; distribute, sublicense, and/or sell copies of this work, and to     ;;;
;;; permit persons to whom this work is furnished to do so, subject to  ;;;
;;; the following conditions:                                           ;;;
;;;  1. The code must retain the above copyright notice, this list of   ;;;
;;;     conditions and the following disclaimer.                        ;;;
;;;  2. Any modifications must be clearly marked as such.               ;;;
;;;  3. Original authors' names are not deleted.                        ;;;
;;;  4. The authors' names are not used to endorse or promote products  ;;;
;;;     derived from this software without specific prior written       ;;;
;;;     permission.                                                     ;;;
;;;                                                                     ;;;
;;; CARNEGIE MELLON UNIVERSITY AND THE CONTRIBUTORS TO THIS WORK        ;;;
;;; DISCLAIM ALL WARRANTIES WITH REGARD TO THIS SOFTWARE, INCLUDING     ;;;
;;; ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS, IN NO EVENT  ;;;
;;; SHALL CARNEGIE MELLON UNIVERSITY NOR THE CONTRIBUTORS BE LIABLE     ;;;
;;; FOR ANY SPECIAL, INDIRECT OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES   ;;;
;;; WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN  ;;;
;;; AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION,         ;;;
;;; ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF      ;;;
;;; THIS SOFTWARE.                                                      ;;;
;;;                                                                     ;;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;;
;;; lexical look up, from words to pronunciations
;;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; 
;;; Modified by Asanka Wasala - Language Technology Research Laboratory, 
;;; University of Colombo School of Computing, Sri Lanka
;;; <awasala@webmail.cmb.ac.lk>
;;; Nov-2006 to Oct-2006
;;;
;;; Sinhala Letter-to-Sound Rules
;;; (based on paper: http://acl.ldc.upenn.edu/P/P06/P06-2114.pdf)
;;;

(require 'ucsc_sin_sdn_syl)  	;; call Syllabification module written by Asanka Wasala (08-08-2005)

(lts.ruleset
 sin_charset
 (  (OCT1 ‡ )
    (OCT2 ∂ )
    ;(OCT3 ö õ ú ù û ü † ° ¢ £ § • ¶ ß ® © ™ ´ ¨ ≠ Æ Ø ∞ ± ≥ ¥ µ ∂ ∑ ∏ π ∫ ª Ω Ä ÅÇ É Ñ Ö Ü) ;; Third Octet of Consonants
    (OCT3 ö õ ú ù û ü † ° ¢ £ § • ¶ ß ® © ™ ´ ¨ ≠ Æ Ø ∞ ± ≥ ¥ µ ∂ ∑ ∏ π ∫ ª Ω ) 
    (OCT6 Ä Å Ç É Ñ Ö Ü)
    
    (OCT4 ∑ )
    (OCT5 í ì ô ù ë è ) ;; Third octet of vowel modifiers i ii e oo aee aa
    (OCT7 â ä ë ï á Ü ) ;; Third octet of vowels i ii e oo aee aa
    (OCT8 Ç É ) 
    (OCT9 í ì ö ê ë ñ)  ;; Third octet of vowels i ii ee uu ae aee
 
 )
 (
  ;; Written by Asanka Wasala (25-08-2006)
  ;; Consonants can be represented by OCT1 OCT2 OCT3 or OCT1 OCT4 OCT6

      ( [ A ] = ae )
      ( [ B ] = b ii)
      ( [ C ] = s ii)
      ( [ D ] = d ii)
	( [ E ] = ii)
	( [ F ] = e f)
	( [ G ] = j ii)
	( [ H ] = e cha)
	( [ I ] = a i)
	( [ J ] = j ee)
	( [ K ] = k ee)
	( [ L ] = e l)
	( [ M ] = e m)
	( [ N ] = e n)
	( [ O ] = oo)
	( [ P ] = p ii)
	( [ Q ] = k i u)
	( [ R ] = aa r)
	( [ S ] = e s)
	( [ T ] = t ii)
	( [ U ] = uu)
	( [ V ] = v ii)
	( [ W ] = d a b l i v)
	( [ X ] = e k s)
	( [ Y ] = v a i)
	( [ Z ] = i s e d)

	( [ a ] = ae )
	( [ b ] = b ii)
	( [ c ] = s ii)
	( [ d ] = d ii)
	( [ e ] = ii)
	( [ f ] = e f)
	( [ g ] = j ii)
	( [ h ] = e cha)
	( [ i ] = a i)
	( [ j ] = j ee)
	( [ k ] = k ee)
	( [ l ] = e l)
	( [ m ] = e m)
	( [ n ] = e n)
	( [ o ] = oo)
	( [ p ] = p ii)
	( [ q ] = k i u)
	( [ r ] = aa r)
	( [ s ] = e s)
	( [ t ] = t ii)
	( [ u ] = uu)
	( [ v ] = v ii)
	( [ w ] = d a b l i v)
	( [ x ] = e k s)
	( [ y ] = v a i)
	( [ z ] = i s e d)
							   
						     



  
  (  [ ‡ ∂ ö ‡ ∂ ª ‡ ∑ î ]  = k a r u )
  (  [ ‡ ∂ ö ‡ ∂ Ω ‡ ∑ î ]  = k a l u )
  (  [ ‡ ∂ ö ‡ ∑ Ö ‡ ∑ î ]  = k a l u )
  
  ( # [ ‡ ∑ É ‡ ∑ ä ‡ ∑ Ä ] OCT1 OCT2 OCT3 = s v aaa )
  ( # [ ‡ ∑ É ‡ ∑ ä ‡ ∑ Ä ] OCT1 OCT4 OCT6 = s v aaa )
  
  ( # [ ‡ ∂ ö ] ‡ ∂ ª ‡ ∂ ≠ ‡ ∑ ä ‡ ∂ ≠ = k a )  		; karaththa
  ( # [ ‡ ∂ ö ] ‡ ∂ ª ‡ ∂ Ø ‡ ∂ ª = k a )        	; karadhaaraaa
  ( # [ ‡ ∂ ö ] ‡ ∂ ª ‡ ∂ ö ‡ ∑ í = k aaa )      	; karaki(yaaa)
  ( # [ ‡ ∂ ö ] ‡ ∂ ª ‡ ∂ ö = k a )              	; karakavana
  ( # [ ‡ ∂ ö ] ‡ ∂ ª ‡ ∂ † = k a )              	; karaccalaya
  ( # [ ‡ ∂ ö ] ‡ ∂ ª OCT1 OCT4 OCT9 = k a )     	; kar (i/ii/ae/aee/ee/uu)
  ( # [ ‡ ∂ ö ] ‡ ∂ ª ‡ ∑ ä = k a )              	; kar   
  ( # [ ‡ ∂ ö ] ‡ ∂ ª = k aaa )
  
  ( OCT1 OCT2 OCT3 [ ‡ ∑ ä ‚ Ä ç ‡ ∂ ª ] ‡ ∑ Ñ = r a )
  ( OCT1 OCT4 OCT6 [ ‡ ∑ ä ‚ Ä ç ‡ ∂ ª ] ‡ ∑ Ñ = r a )
  ( OCT1 OCT2 OCT3 [ ‡ ∑ ä ‚ Ä ç ‡ ∂ ª ] OCT1 OCT2 OCT3 = r aaa )
  ( OCT1 OCT4 OCT6 [ ‡ ∑ ä ‚ Ä ç ‡ ∂ ª ] OCT1 OCT4 OCT6 = r aaa )

  ( OCT1 OCT4 OCT5 [ ‡ ∑ Ñ ] OCT1 OCT2 OCT3 = h aaa )
  ( OCT1 OCT4 OCT5 [ ‡ ∑ Ñ ] OCT1 OCT4 OCT6 = h aaa )
  ( OCT1 OCT4 OCT5 [ ‡ ∑ Ñ ] # = h aaa )
  
  ( OCT1 OCT2 OCT7 [ ‡ ∑ Ñ ] OCT1 OCT2 OCT3 = h aaa )
  ( OCT1 OCT2 OCT7 [ ‡ ∑ Ñ ] OCT1 OCT4 OCT6 = h aaa )
  ( OCT1 OCT2 OCT7 [ ‡ ∑ Ñ ] # = h aaa )
  
  ( [ ‡ ∑ Ñ ] OCT1 OCT2 OCT3 = h a )
  ( [ ‡ ∑ Ñ ] OCT1 OCT4 OCT6 = h a )

 ( [ ‡ ∑ è ] = aa aa )
 ( [ ‡ ∑ ñ ] = uu uu )
 ( [ ‡ ∑ î ] = u )
 ( [ ‡ ∑ ≤ ] = r uu )
 ( [ ‡ ∑ í ] = i )
 ( [ ‡ ∑ ì ] = ii ii )
 ( [ ‡ ∑ ê ] = ae )
 ( [ ‡ ∑ ë ] = aee aee )
 ( [ ‡ ∑ û ] = a u )
 ( [ ‡ ∑ ü ] = a u )
 ( [ ‡ ∑ ú ] = o )
 ( [ ‡ ∑ ù ] = oo oo )
 ( [ ‡ ∑ ö ] = ee ee)
 ( [ ‡ ∑ õ ] = a i )
 ( [ ‡ ∑ ò ] = r u )
 ( [ ‡ ∑ ≥ ] = a uu )
 ( [ ‡ ∑ ô ] = e )
 
 ( # [ ‡ ∑ Ü ] # = f aaa )
 ( # [ ‡ ∑ Ñ ] # = h aaa )
 ( # [ ‡ ∑ Ö ] # = l aaa )
 ( # [ ‡ ∑ Ç ] # = sha aaa )
 ( # [ ‡ ∑ É ] # = s aaa )
 ( # [ ‡ ∑ Ä ] # = v aaa )
 ( # [ ‡ ∑ Å ] # = sha aaa )
 ( # [ ‡ ∂ É ] # = a h )
 ( # [ ‡ ∂ Ç ] # = a on )
 ( # [ ‡ ∂ õ ] # = k aaa )
 ( # [ ‡ ∂ ö ] # = k aaa )
 ( # [ ‡ ∂ ù ] # = g aaa )
 ( # [ ‡ ∂ ú ] # = g aaa )
 ( # [ ‡ ∂ ü ] # = sg aaa )
 ( # [ ‡ ∂ û ] # = on aaa )
 ( # [ ‡ ∂ ° ] # = cha aaa )
 ( # [ ‡ ∂ † ] # = cha aaa )
 ( # [ ‡ ∂ £ ] # = j aaa )
 ( # [ ‡ ∂ ¢ ] # = j aaa )
 ( # [ ‡ ∂ • ] # = j nga aaa )
 ( # [ ‡ ∂ § ] # = nga aaa )
 ( # [ ‡ ∂ ß ] # = t aaa )
 ( # [ ‡ ∂ ¶ ] # = j aaa )
 ( # [ ‡ ∂ © ] # = d aaa )
 ( # [ ‡ ∂ ® ] # = t aaa )
 ( # [ ‡ ∂ ´ ] # = n aaa )
 ( # [ ‡ ∂ ™ ] # = d aaa )
 ( # [ ‡ ∂ ≠ ] # = tha aaa )
 ( # [ ‡ ∂ ¨ ] # = sd aaa )
 ( # [ ‡ ∂ Ø ] # = dha aaa )
 ( # [ ‡ ∂ Æ ] # = tha aaa )
 ( # [ ‡ ∂ ± ] # = n aaa )
 ( # [ ‡ ∂ ∞ ] # = dha aaa )
 ( # [ ‡ ∂ ≥ ] # = sdha aaa )
 ( # [ ‡ ∂ µ ] # = p aaa )
 ( # [ ‡ ∂ ¥ ] # = p aaa )
 ( # [ ‡ ∂ ∑ ] # = b aaa )
 ( # [ ‡ ∂ ∂ ] # = b aaa )
 ( # [ ‡ ∂ π ] # = sba aaa )
 ( # [ ‡ ∂ ∏ ] # = m aaa )
 ( # [ ‡ ∂ ª ] # = r aaa )
 ( # [ ‡ ∂ ∫ ] # = y aaa )
 ( # [ ‡ ∂ Ω ] # = l aaa )
 
 ( [ ‡ ∑ Ü ] ‡ ∂ ∫ ‡ ∑ í # = f a y i)
 ( [ ‡ ∑ Ñ ] ‡ ∂ ∫ ‡ ∑ í # = h a y i)
 ( [ ‡ ∑ Ö ] ‡ ∂ ∫ ‡ ∑ í # = l a y i)
 ( [ ‡ ∑ Ç ] ‡ ∂ ∫ ‡ ∑ í # = sha a y i)
 ( [ ‡ ∑ É ] ‡ ∂ ∫ ‡ ∑ í # = s a y i)
 ( [ ‡ ∑ Ä ] ‡ ∂ ∫ ‡ ∑ í # = v a y i)
 ( [ ‡ ∑ Å ] ‡ ∂ ∫ ‡ ∑ í # = sha a y i)
 ( [ ‡ ∂ õ ] ‡ ∂ ∫ ‡ ∑ í # = k a y i)
 ( [ ‡ ∂ ö ] ‡ ∂ ∫ ‡ ∑ í # = k a y i)
 ( [ ‡ ∂ ù ] ‡ ∂ ∫ ‡ ∑ í # = g a y i)
 ( [ ‡ ∂ ú ] ‡ ∂ ∫ ‡ ∑ í # = g a y i)
 ( [ ‡ ∂ ü ] ‡ ∂ ∫ ‡ ∑ í # = sg a y i)
 ( [ ‡ ∂ û ] ‡ ∂ ∫ ‡ ∑ í # = on a y i)
 ( [ ‡ ∂ ° ] ‡ ∂ ∫ ‡ ∑ í # = cha a y i)
 ( [ ‡ ∂ † ] ‡ ∂ ∫ ‡ ∑ í # = cha a y i)
 ( [ ‡ ∂ £ ] ‡ ∂ ∫ ‡ ∑ í # = j a y i)
 ( [ ‡ ∂ ¢ ] ‡ ∂ ∫ ‡ ∑ í # = j a y i)
 ( [ ‡ ∂ • ] ‡ ∂ ∫ ‡ ∑ í # = j nga a y i)
 ( [ ‡ ∂ § ] ‡ ∂ ∫ ‡ ∑ í # = nga a y i)
 ( [ ‡ ∂ ß ] ‡ ∂ ∫ ‡ ∑ í # = t a y i)
 ( [ ‡ ∂ ¶ ] ‡ ∂ ∫ ‡ ∑ í # = j a y i)
 ( [ ‡ ∂ © ] ‡ ∂ ∫ ‡ ∑ í # = d a y i)
 ( [ ‡ ∂ ® ] ‡ ∂ ∫ ‡ ∑ í # = t a y i)
 ( [ ‡ ∂ ´ ] ‡ ∂ ∫ ‡ ∑ í # = n a y i)
 ( [ ‡ ∂ ™ ] ‡ ∂ ∫ ‡ ∑ í # = d a y i)
 ( [ ‡ ∂ ≠ ] ‡ ∂ ∫ ‡ ∑ í # = tha a y i)
 ( [ ‡ ∂ ¨ ] ‡ ∂ ∫ ‡ ∑ í # = sd a y i)
 ( [ ‡ ∂ Ø ] ‡ ∂ ∫ ‡ ∑ í # = dha a y i)
 ( [ ‡ ∂ Æ ] ‡ ∂ ∫ ‡ ∑ í # = tha a y i)
 ( [ ‡ ∂ ± ] ‡ ∂ ∫ ‡ ∑ í # = n a y i)
 ( [ ‡ ∂ ∞ ] ‡ ∂ ∫ ‡ ∑ í # = dha a y i)
 ( [ ‡ ∂ ≥ ] ‡ ∂ ∫ ‡ ∑ í # = sdha a y i)
 ( [ ‡ ∂ µ ] ‡ ∂ ∫ ‡ ∑ í # = p a y i)
 ( [ ‡ ∂ ¥ ] ‡ ∂ ∫ ‡ ∑ í # = p a y i)
 ( [ ‡ ∂ ∑ ] ‡ ∂ ∫ ‡ ∑ í # = b a y i)
 ( [ ‡ ∂ ∂ ] ‡ ∂ ∫ ‡ ∑ í # = b a y i)
 ( [ ‡ ∂ π ] ‡ ∂ ∫ ‡ ∑ í # = sba a y i)
 ( [ ‡ ∂ ∏ ] ‡ ∂ ∫ ‡ ∑ í # = m a y i)
 ( [ ‡ ∂ ª ] ‡ ∂ ∫ ‡ ∑ í # = r a y i)
 ( [ ‡ ∂ ∫ ] ‡ ∂ ∫ ‡ ∑ í # = y a y i)
 ( [ ‡ ∂ Ω ] ‡ ∂ ∫ ‡ ∑ í # = l a y i)
 
 
 ( [ ‡ ∑ Ü ] ‡ ∂ ª ‡ ∑ ä # = f aaa r )
 ( [ ‡ ∑ Ñ ] ‡ ∂ ª ‡ ∑ ä # = h aaa r )
 ( [ ‡ ∑ Ö ] ‡ ∂ ª ‡ ∑ ä # = l aaa r )
 ( [ ‡ ∑ Ç ] ‡ ∂ ª ‡ ∑ ä # = sha aaa r )
 ( [ ‡ ∑ É ] ‡ ∂ ª ‡ ∑ ä # = s aaa r )
 ( [ ‡ ∑ Ä ] ‡ ∂ ª ‡ ∑ ä # = v aaa r )
 ( [ ‡ ∑ Å ] ‡ ∂ ª ‡ ∑ ä # = sha aaa r )
 ( [ ‡ ∂ õ ] ‡ ∂ ª ‡ ∑ ä # = k aaa r )
 ( [ ‡ ∂ ö ] ‡ ∂ ª ‡ ∑ ä # = k aaa r )
 ( [ ‡ ∂ ù ] ‡ ∂ ª ‡ ∑ ä # = g aaa r )
 ( [ ‡ ∂ ú ] ‡ ∂ ª ‡ ∑ ä # = g aaa r )
 ( [ ‡ ∂ ü ] ‡ ∂ ª ‡ ∑ ä # = sg aaa r )
 ( [ ‡ ∂ û ] ‡ ∂ ª ‡ ∑ ä # = on aaa r )
 ( [ ‡ ∂ ° ] ‡ ∂ ª ‡ ∑ ä # = cha aaa r )
 ( [ ‡ ∂ † ] ‡ ∂ ª ‡ ∑ ä # = cha aaa r )
 ( [ ‡ ∂ £ ] ‡ ∂ ª ‡ ∑ ä # = j aaa r )
 ( [ ‡ ∂ ¢ ] ‡ ∂ ª ‡ ∑ ä # = j aaa r )
 ( [ ‡ ∂ • ] ‡ ∂ ª ‡ ∑ ä # = j nga aaa r )
 ( [ ‡ ∂ § ] ‡ ∂ ª ‡ ∑ ä # = nga aaa r )
 ( [ ‡ ∂ ß ] ‡ ∂ ª ‡ ∑ ä # = t aaa r )
 ( [ ‡ ∂ ¶ ] ‡ ∂ ª ‡ ∑ ä # = j aaa r )
 ( [ ‡ ∂ © ] ‡ ∂ ª ‡ ∑ ä # = d aaa r )
 ( [ ‡ ∂ ® ] ‡ ∂ ª ‡ ∑ ä # = t aaa r )
 ( [ ‡ ∂ ´ ] ‡ ∂ ª ‡ ∑ ä # = n aaa r )
 ( [ ‡ ∂ ™ ] ‡ ∂ ª ‡ ∑ ä # = d aaa r )
 ( [ ‡ ∂ ≠ ] ‡ ∂ ª ‡ ∑ ä # = tha aaa r )
 ( [ ‡ ∂ ¨ ] ‡ ∂ ª ‡ ∑ ä # = sd aaa r )
 ( [ ‡ ∂ Ø ] ‡ ∂ ª ‡ ∑ ä # = dha aaa r )
 ( [ ‡ ∂ Æ ] ‡ ∂ ª ‡ ∑ ä # = tha aaa r )
 ( [ ‡ ∂ ± ] ‡ ∂ ª ‡ ∑ ä # = n aaa r )
 ( [ ‡ ∂ ∞ ] ‡ ∂ ª ‡ ∑ ä # = dha aaa r )
 ( [ ‡ ∂ ≥ ] ‡ ∂ ª ‡ ∑ ä # = sdha aaa r )
 ( [ ‡ ∂ µ ] ‡ ∂ ª ‡ ∑ ä # = p aaa r )
 ( [ ‡ ∂ ¥ ] ‡ ∂ ª ‡ ∑ ä # = p aaa r )
 ( [ ‡ ∂ ∑ ] ‡ ∂ ª ‡ ∑ ä # = b aaa r )
 ( [ ‡ ∂ ∂ ] ‡ ∂ ª ‡ ∑ ä # = b aaa r )
 ( [ ‡ ∂ π ] ‡ ∂ ª ‡ ∑ ä # = sba aaa r )
 ( [ ‡ ∂ ∏ ] ‡ ∂ ª ‡ ∑ ä # = m aaa r )
 ( [ ‡ ∂ ª ] ‡ ∂ ª ‡ ∑ ä # = r aaa r )
 ( [ ‡ ∂ ∫ ] ‡ ∂ ª ‡ ∑ ä # = y aaa r )
 ( [ ‡ ∂ Ω ] ‡ ∂ ª ‡ ∑ ä # = l aaa r )
 
 ( [ ‡ ∑ Ü ] ‡ ∂ ∂ ‡ ∑ ä # = f aaa b )
 ( [ ‡ ∑ Ñ ] ‡ ∂ ∂ ‡ ∑ ä # = h aaa b )
 ( [ ‡ ∑ Ö ] ‡ ∂ ∂ ‡ ∑ ä # = l aaa b )
 ( [ ‡ ∑ Ç ] ‡ ∂ ∂ ‡ ∑ ä # = sha aaa b )
 ( [ ‡ ∑ É ] ‡ ∂ ∂ ‡ ∑ ä # = s aaa b )
 ( [ ‡ ∑ Ä ] ‡ ∂ ∂ ‡ ∑ ä # = v aaa b )
 ( [ ‡ ∑ Å ] ‡ ∂ ∂ ‡ ∑ ä # = sha aaa b )
 ( [ ‡ ∂ õ ] ‡ ∂ ∂ ‡ ∑ ä # = k aaa b )
 ( [ ‡ ∂ ö ] ‡ ∂ ∂ ‡ ∑ ä # = k aaa b )
 ( [ ‡ ∂ ù ] ‡ ∂ ∂ ‡ ∑ ä # = g aaa b )
 ( [ ‡ ∂ ú ] ‡ ∂ ∂ ‡ ∑ ä # = g aaa b )
 ( [ ‡ ∂ ü ] ‡ ∂ ∂ ‡ ∑ ä # = sg aaa b )
 ( [ ‡ ∂ û ] ‡ ∂ ∂ ‡ ∑ ä # = on aaa b )
 ( [ ‡ ∂ ° ] ‡ ∂ ∂ ‡ ∑ ä # = cha aaa b )
 ( [ ‡ ∂ † ] ‡ ∂ ∂ ‡ ∑ ä # = cha aaa b )
 ( [ ‡ ∂ £ ] ‡ ∂ ∂ ‡ ∑ ä # = j aaa b )
 ( [ ‡ ∂ ¢ ] ‡ ∂ ∂ ‡ ∑ ä # = j aaa b )
 ( [ ‡ ∂ • ] ‡ ∂ ∂ ‡ ∑ ä # = j nga aaa b )
 ( [ ‡ ∂ § ] ‡ ∂ ∂ ‡ ∑ ä # = nga aaa b )
 ( [ ‡ ∂ ß ] ‡ ∂ ∂ ‡ ∑ ä # = t aaa b )
 ( [ ‡ ∂ ¶ ] ‡ ∂ ∂ ‡ ∑ ä # = j aaa b )
 ( [ ‡ ∂ © ] ‡ ∂ ∂ ‡ ∑ ä # = d aaa b )
 ( [ ‡ ∂ ® ] ‡ ∂ ∂ ‡ ∑ ä # = t aaa b )
 ( [ ‡ ∂ ´ ] ‡ ∂ ∂ ‡ ∑ ä # = n aaa b )
 ( [ ‡ ∂ ™ ] ‡ ∂ ∂ ‡ ∑ ä # = d aaa b )
 ( [ ‡ ∂ ≠ ] ‡ ∂ ∂ ‡ ∑ ä # = tha aaa b )
 ( [ ‡ ∂ ¨ ] ‡ ∂ ∂ ‡ ∑ ä # = sd aaa b )
 ( [ ‡ ∂ Ø ] ‡ ∂ ∂ ‡ ∑ ä # = dha aaa b )
 ( [ ‡ ∂ Æ ] ‡ ∂ ∂ ‡ ∑ ä # = tha aaa b )
 ( [ ‡ ∂ ± ] ‡ ∂ ∂ ‡ ∑ ä # = n aaa b )
 ( [ ‡ ∂ ∞ ] ‡ ∂ ∂ ‡ ∑ ä # = dha aaa b )
 ( [ ‡ ∂ ≥ ] ‡ ∂ ∂ ‡ ∑ ä # = sdha aaa b )
 ( [ ‡ ∂ µ ] ‡ ∂ ∂ ‡ ∑ ä # = p aaa b )
 ( [ ‡ ∂ ¥ ] ‡ ∂ ∂ ‡ ∑ ä # = p aaa b )
 ( [ ‡ ∂ ∑ ] ‡ ∂ ∂ ‡ ∑ ä # = b aaa b )
 ( [ ‡ ∂ ∂ ] ‡ ∂ ∂ ‡ ∑ ä # = b aaa b )
 ( [ ‡ ∂ π ] ‡ ∂ ∂ ‡ ∑ ä # = sba aaa b )
 ( [ ‡ ∂ ∏ ] ‡ ∂ ∂ ‡ ∑ ä # = m aaa b )
 ( [ ‡ ∂ ª ] ‡ ∂ ∂ ‡ ∑ ä # = r aaa b )
 ( [ ‡ ∂ ∫ ] ‡ ∂ ∂ ‡ ∑ ä # = y aaa b )
 ( [ ‡ ∂ Ω ] ‡ ∂ ∂ ‡ ∑ ä # = l aaa b )
 
 ( [ ‡ ∑ Ü ] ‡ ∂ © ‡ ∑ ä # = f aaa d )
 ( [ ‡ ∑ Ñ ] ‡ ∂ © ‡ ∑ ä # = h aaa d )
 ( [ ‡ ∑ Ö ] ‡ ∂ © ‡ ∑ ä # = l aaa d )
 ( [ ‡ ∑ Ç ] ‡ ∂ © ‡ ∑ ä # = sha aaa d )
 ( [ ‡ ∑ É ] ‡ ∂ © ‡ ∑ ä # = s aaa d )
 ( [ ‡ ∑ Ä ] ‡ ∂ © ‡ ∑ ä # = v aaa d )
 ( [ ‡ ∑ Å ] ‡ ∂ © ‡ ∑ ä # = sha aaa d )
 ( [ ‡ ∂ õ ] ‡ ∂ © ‡ ∑ ä # = k aaa d )
 ( [ ‡ ∂ ö ] ‡ ∂ © ‡ ∑ ä # = k aaa d )
 ( [ ‡ ∂ ù ] ‡ ∂ © ‡ ∑ ä # = g aaa d )
 ( [ ‡ ∂ ú ] ‡ ∂ © ‡ ∑ ä # = g aaa d )
 ( [ ‡ ∂ ü ] ‡ ∂ © ‡ ∑ ä # = sg aaa d )
 ( [ ‡ ∂ û ] ‡ ∂ © ‡ ∑ ä # = on aaa d )
 ( [ ‡ ∂ ° ] ‡ ∂ © ‡ ∑ ä # = cha aaa d )
 ( [ ‡ ∂ † ] ‡ ∂ © ‡ ∑ ä # = cha aaa d )
 ( [ ‡ ∂ £ ] ‡ ∂ © ‡ ∑ ä # = j aaa d )
 ( [ ‡ ∂ ¢ ] ‡ ∂ © ‡ ∑ ä # = j aaa d )
 ( [ ‡ ∂ • ] ‡ ∂ © ‡ ∑ ä # = j nga aaa d )
 ( [ ‡ ∂ § ] ‡ ∂ © ‡ ∑ ä # = nga aaa d )
 ( [ ‡ ∂ ß ] ‡ ∂ © ‡ ∑ ä # = t aaa d )
 ( [ ‡ ∂ ¶ ] ‡ ∂ © ‡ ∑ ä # = j aaa d )
 ( [ ‡ ∂ © ] ‡ ∂ © ‡ ∑ ä # = d aaa d )
 ( [ ‡ ∂ ® ] ‡ ∂ © ‡ ∑ ä # = t aaa d )
 ( [ ‡ ∂ ´ ] ‡ ∂ © ‡ ∑ ä # = n aaa d )
 ( [ ‡ ∂ ™ ] ‡ ∂ © ‡ ∑ ä # = d aaa d )
 ( [ ‡ ∂ ≠ ] ‡ ∂ © ‡ ∑ ä # = tha aaa d )
 ( [ ‡ ∂ ¨ ] ‡ ∂ © ‡ ∑ ä # = sd aaa d )
 ( [ ‡ ∂ Ø ] ‡ ∂ © ‡ ∑ ä # = dha aaa d )
 ( [ ‡ ∂ Æ ] ‡ ∂ © ‡ ∑ ä # = tha aaa d )
 ( [ ‡ ∂ ± ] ‡ ∂ © ‡ ∑ ä # = n aaa d )
 ( [ ‡ ∂ ∞ ] ‡ ∂ © ‡ ∑ ä # = dha aaa d )
 ( [ ‡ ∂ ≥ ] ‡ ∂ © ‡ ∑ ä # = sdha aaa d )
 ( [ ‡ ∂ µ ] ‡ ∂ © ‡ ∑ ä # = p aaa d )
 ( [ ‡ ∂ ¥ ] ‡ ∂ © ‡ ∑ ä # = p aaa d )
 ( [ ‡ ∂ ∑ ] ‡ ∂ © ‡ ∑ ä # = b aaa d )
 ( [ ‡ ∂ ∂ ] ‡ ∂ © ‡ ∑ ä # = b aaa d )
 ( [ ‡ ∂ π ] ‡ ∂ © ‡ ∑ ä # = sba aaa d )
 ( [ ‡ ∂ ∏ ] ‡ ∂ © ‡ ∑ ä # = m aaa d )
 ( [ ‡ ∂ ª ] ‡ ∂ © ‡ ∑ ä # = r aaa d )
 ( [ ‡ ∂ ∫ ] ‡ ∂ © ‡ ∑ ä # = y aaa d )
 ( [ ‡ ∂ Ω ] ‡ ∂ © ‡ ∑ ä # = l aaa d )
 
 ( [ ‡ ∑ Ü ] ‡ ∂ ß ‡ ∑ ä # = f aaa t )
 ( [ ‡ ∑ Ñ ] ‡ ∂ ß ‡ ∑ ä # = h aaa t )
 ( [ ‡ ∑ Ö ] ‡ ∂ ß ‡ ∑ ä # = l aaa t )
 ( [ ‡ ∑ Ç ] ‡ ∂ ß ‡ ∑ ä # = sha aaa t )
 ( [ ‡ ∑ É ] ‡ ∂ ß ‡ ∑ ä # = s aaa t )
 ( [ ‡ ∑ Ä ] ‡ ∂ ß ‡ ∑ ä # = v aaa t )
 ( [ ‡ ∑ Å ] ‡ ∂ ß ‡ ∑ ä # = sha aaa t )
 ( [ ‡ ∂ õ ] ‡ ∂ ß ‡ ∑ ä # = k aaa t )
 ( [ ‡ ∂ ö ] ‡ ∂ ß ‡ ∑ ä # = k aaa t )
 ( [ ‡ ∂ ù ] ‡ ∂ ß ‡ ∑ ä # = g aaa t )
 ( [ ‡ ∂ ú ] ‡ ∂ ß ‡ ∑ ä # = g aaa t )
 ( [ ‡ ∂ ü ] ‡ ∂ ß ‡ ∑ ä # = sg aaa t )
 ( [ ‡ ∂ û ] ‡ ∂ ß ‡ ∑ ä # = on aaa t )
 ( [ ‡ ∂ ° ] ‡ ∂ ß ‡ ∑ ä # = cha aaa t )
 ( [ ‡ ∂ † ] ‡ ∂ ß ‡ ∑ ä # = cha aaa t )
 ( [ ‡ ∂ £ ] ‡ ∂ ß ‡ ∑ ä # = j aaa t )
 ( [ ‡ ∂ ¢ ] ‡ ∂ ß ‡ ∑ ä # = j aaa t )
 ( [ ‡ ∂ • ] ‡ ∂ ß ‡ ∑ ä # = j nga aaa t )
 ( [ ‡ ∂ § ] ‡ ∂ ß ‡ ∑ ä # = nga aaa t )
 ( [ ‡ ∂ ß ] ‡ ∂ ß ‡ ∑ ä # = t aaa t )
 ( [ ‡ ∂ ¶ ] ‡ ∂ ß ‡ ∑ ä # = j aaa t )
 ( [ ‡ ∂ © ] ‡ ∂ ß ‡ ∑ ä # = d aaa t )
 ( [ ‡ ∂ ® ] ‡ ∂ ß ‡ ∑ ä # = t aaa t )
 ( [ ‡ ∂ ´ ] ‡ ∂ ß ‡ ∑ ä # = n aaa t )
 ( [ ‡ ∂ ™ ] ‡ ∂ ß ‡ ∑ ä # = d aaa t )
 ( [ ‡ ∂ ≠ ] ‡ ∂ ß ‡ ∑ ä # = tha aaa t )
 ( [ ‡ ∂ ¨ ] ‡ ∂ ß ‡ ∑ ä # = sd aaa t )
 ( [ ‡ ∂ Ø ] ‡ ∂ ß ‡ ∑ ä # = dha aaa t )
 ( [ ‡ ∂ Æ ] ‡ ∂ ß ‡ ∑ ä # = tha aaa t )
 ( [ ‡ ∂ ± ] ‡ ∂ ß ‡ ∑ ä # = n aaa t )
 ( [ ‡ ∂ ∞ ] ‡ ∂ ß ‡ ∑ ä # = dha aaa t )
 ( [ ‡ ∂ ≥ ] ‡ ∂ ß ‡ ∑ ä # = sdha aaa t )
 ( [ ‡ ∂ µ ] ‡ ∂ ß ‡ ∑ ä # = p aaa t )
 ( [ ‡ ∂ ¥ ] ‡ ∂ ß ‡ ∑ ä # = p aaa t )
 ( [ ‡ ∂ ∑ ] ‡ ∂ ß ‡ ∑ ä # = b aaa t )
 ( [ ‡ ∂ ∂ ] ‡ ∂ ß ‡ ∑ ä # = b aaa t )
 ( [ ‡ ∂ π ] ‡ ∂ ß ‡ ∑ ä # = sba aaa t )
 ( [ ‡ ∂ ∏ ] ‡ ∂ ß ‡ ∑ ä # = m aaa t )
 ( [ ‡ ∂ ª ] ‡ ∂ ß ‡ ∑ ä # = r aaa t )
 ( [ ‡ ∂ ∫ ] ‡ ∂ ß ‡ ∑ ä # = y aaa t )
 ( [ ‡ ∂ Ω ] ‡ ∂ ß ‡ ∑ ä # = l aaa t )
 
 ( [ ‡ ∑ Ü ] OCT1 OCT2 OCT3 ‡ ∑ ä = f a )
 ( [ ‡ ∑ Ñ ] OCT1 OCT2 OCT3 ‡ ∑ ä = h a )
 ( [ ‡ ∑ Ö ] OCT1 OCT2 OCT3 ‡ ∑ ä = l a )
 ( [ ‡ ∑ Ç ] OCT1 OCT2 OCT3 ‡ ∑ ä = sha a )
 ( [ ‡ ∑ É ] OCT1 OCT2 OCT3 ‡ ∑ ä = s a )
 ( [ ‡ ∑ Ä ] OCT1 OCT2 OCT3 ‡ ∑ ä = v a )
 ( [ ‡ ∑ Å ] OCT1 OCT2 OCT3 ‡ ∑ ä = sha a )
 ( [ ‡ ∂ õ ] OCT1 OCT2 OCT3 ‡ ∑ ä = k a )
 ( [ ‡ ∂ ö ] OCT1 OCT2 OCT3 ‡ ∑ ä = k a )
 ( [ ‡ ∂ ù ] OCT1 OCT2 OCT3 ‡ ∑ ä = g a )
 ( [ ‡ ∂ ú ] OCT1 OCT2 OCT3 ‡ ∑ ä = g a )
 ( [ ‡ ∂ ü ] OCT1 OCT2 OCT3 ‡ ∑ ä = sg a )
 ( [ ‡ ∂ û ] OCT1 OCT2 OCT3 ‡ ∑ ä = on a )
 ( [ ‡ ∂ ° ] OCT1 OCT2 OCT3 ‡ ∑ ä = cha a )
 ( [ ‡ ∂ † ] OCT1 OCT2 OCT3 ‡ ∑ ä = cha a )
 ( [ ‡ ∂ £ ] OCT1 OCT2 OCT3 ‡ ∑ ä = j a )
 ( [ ‡ ∂ ¢ ] OCT1 OCT2 OCT3 ‡ ∑ ä = j a )
 ( [ ‡ ∂ • ] OCT1 OCT2 OCT3 ‡ ∑ ä = j nga a )
 ( [ ‡ ∂ § ] OCT1 OCT2 OCT3 ‡ ∑ ä = nga a )
 ( [ ‡ ∂ ß ] OCT1 OCT2 OCT3 ‡ ∑ ä = t a )
 ( [ ‡ ∂ ¶ ] OCT1 OCT2 OCT3 ‡ ∑ ä = j a )
 ( [ ‡ ∂ © ] OCT1 OCT2 OCT3 ‡ ∑ ä = d a )
 ( [ ‡ ∂ ® ] OCT1 OCT2 OCT3 ‡ ∑ ä = t a )
 ( [ ‡ ∂ ´ ] OCT1 OCT2 OCT3 ‡ ∑ ä = n a )
 ( [ ‡ ∂ ™ ] OCT1 OCT2 OCT3 ‡ ∑ ä = d a )
 ( [ ‡ ∂ ≠ ] OCT1 OCT2 OCT3 ‡ ∑ ä = tha a )
 ( [ ‡ ∂ ¨ ] OCT1 OCT2 OCT3 ‡ ∑ ä = sd a )
 ( [ ‡ ∂ Ø ] OCT1 OCT2 OCT3 ‡ ∑ ä = dha a )
 ( [ ‡ ∂ Æ ] OCT1 OCT2 OCT3 ‡ ∑ ä = tha a )
 ( [ ‡ ∂ ± ] OCT1 OCT2 OCT3 ‡ ∑ ä = n a )
 ( [ ‡ ∂ ∞ ] OCT1 OCT2 OCT3 ‡ ∑ ä = dha a )
 ( [ ‡ ∂ ≥ ] OCT1 OCT2 OCT3 ‡ ∑ ä = sdha a )
 ( [ ‡ ∂ µ ] OCT1 OCT2 OCT3 ‡ ∑ ä = p a )
 ( [ ‡ ∂ ¥ ] OCT1 OCT2 OCT3 ‡ ∑ ä = p a )
 ( [ ‡ ∂ ∑ ] OCT1 OCT2 OCT3 ‡ ∑ ä = b a )
 ( [ ‡ ∂ ∂ ] OCT1 OCT2 OCT3 ‡ ∑ ä = b a )
 ( [ ‡ ∂ π ] OCT1 OCT2 OCT3 ‡ ∑ ä = sba a )
 ( [ ‡ ∂ ∏ ] OCT1 OCT2 OCT3 ‡ ∑ ä = m a )
 ( [ ‡ ∂ ª ] OCT1 OCT2 OCT3 ‡ ∑ ä = r a )
 ( [ ‡ ∂ ∫ ] OCT1 OCT2 OCT3 ‡ ∑ ä = y a )
 ( [ ‡ ∂ Ω ] OCT1 OCT2 OCT3 ‡ ∑ ä = l a )

 ( [ ‡ ∑ Ü ] OCT1 OCT4 OCT6 ‡ ∑ ä = f a )
 ( [ ‡ ∑ Ñ ] OCT1 OCT4 OCT6 ‡ ∑ ä = h a )
 ( [ ‡ ∑ Ö ] OCT1 OCT4 OCT6 ‡ ∑ ä = l a )
 ( [ ‡ ∑ Ç ] OCT1 OCT4 OCT6 ‡ ∑ ä = sha a )
 ( [ ‡ ∑ É ] OCT1 OCT4 OCT6 ‡ ∑ ä = s a )
 ( [ ‡ ∑ Ä ] OCT1 OCT4 OCT6 ‡ ∑ ä = v a )
 ( [ ‡ ∑ Å ] OCT1 OCT4 OCT6 ‡ ∑ ä = sha a )
 ( [ ‡ ∂ õ ] OCT1 OCT4 OCT6 ‡ ∑ ä = k a )
 ( [ ‡ ∂ ö ] OCT1 OCT4 OCT6 ‡ ∑ ä = k a )
 ( [ ‡ ∂ ù ] OCT1 OCT4 OCT6 ‡ ∑ ä = g a )
 ( [ ‡ ∂ ú ] OCT1 OCT4 OCT6 ‡ ∑ ä = g a )
 ( [ ‡ ∂ ü ] OCT1 OCT4 OCT6 ‡ ∑ ä = sg a )
 ( [ ‡ ∂ û ] OCT1 OCT4 OCT6 ‡ ∑ ä = on a )
 ( [ ‡ ∂ ° ] OCT1 OCT4 OCT6 ‡ ∑ ä = cha a )
 ( [ ‡ ∂ † ] OCT1 OCT4 OCT6 ‡ ∑ ä = cha a )
 ( [ ‡ ∂ £ ] OCT1 OCT4 OCT6 ‡ ∑ ä = j a )
 ( [ ‡ ∂ ¢ ] OCT1 OCT4 OCT6 ‡ ∑ ä = j a )
 ( [ ‡ ∂ • ] OCT1 OCT4 OCT6 ‡ ∑ ä = j nga a )
 ( [ ‡ ∂ § ] OCT1 OCT4 OCT6 ‡ ∑ ä = nga a )
 ( [ ‡ ∂ ß ] OCT1 OCT4 OCT6 ‡ ∑ ä = t a )
 ( [ ‡ ∂ ¶ ] OCT1 OCT4 OCT6 ‡ ∑ ä = j a )
 ( [ ‡ ∂ © ] OCT1 OCT4 OCT6 ‡ ∑ ä = d a )
 ( [ ‡ ∂ ® ] OCT1 OCT4 OCT6 ‡ ∑ ä = t a )
 ( [ ‡ ∂ ´ ] OCT1 OCT4 OCT6 ‡ ∑ ä = n a )
 ( [ ‡ ∂ ™ ] OCT1 OCT4 OCT6 ‡ ∑ ä = d a )
 ( [ ‡ ∂ ≠ ] OCT1 OCT4 OCT6 ‡ ∑ ä = tha a )
 ( [ ‡ ∂ ¨ ] OCT1 OCT4 OCT6 ‡ ∑ ä = sd a )
 ( [ ‡ ∂ Ø ] OCT1 OCT4 OCT6 ‡ ∑ ä = dha a )
 ( [ ‡ ∂ Æ ] OCT1 OCT4 OCT6 ‡ ∑ ä = tha a )
 ( [ ‡ ∂ ± ] OCT1 OCT4 OCT6 ‡ ∑ ä = n a )
 ( [ ‡ ∂ ∞ ] OCT1 OCT4 OCT6 ‡ ∑ ä = dha a )
 ( [ ‡ ∂ ≥ ] OCT1 OCT4 OCT6 ‡ ∑ ä = sdha a )
 ( [ ‡ ∂ µ ] OCT1 OCT4 OCT6 ‡ ∑ ä = p a )
 ( [ ‡ ∂ ¥ ] OCT1 OCT4 OCT6 ‡ ∑ ä = p a )
 ( [ ‡ ∂ ∑ ] OCT1 OCT4 OCT6 ‡ ∑ ä = b a )
 ( [ ‡ ∂ ∂ ] OCT1 OCT4 OCT6 ‡ ∑ ä = b a )
 ( [ ‡ ∂ π ] OCT1 OCT4 OCT6 ‡ ∑ ä = sba a )
 ( [ ‡ ∂ ∏ ] OCT1 OCT4 OCT6 ‡ ∑ ä = m a )
 ( [ ‡ ∂ ª ] OCT1 OCT4 OCT6 ‡ ∑ ä = r a )
 ( [ ‡ ∂ ∫ ] OCT1 OCT4 OCT6 ‡ ∑ ä = y a )
 ( [ ‡ ∂ Ω ] OCT1 OCT4 OCT6 ‡ ∑ ä = l a )
 
 ;; anusvaaraya visargaya {
 ( [ ‡ ∑ Ü ] OCT1 OCT2 OCT8  = f a )
 ( [ ‡ ∑ Ñ ] OCT1 OCT2 OCT8  = h a )
 ( [ ‡ ∑ Ö ] OCT1 OCT2 OCT8  = l a )
 ( [ ‡ ∑ Ç ] OCT1 OCT2 OCT8  = sha a )
 ( [ ‡ ∑ É ] OCT1 OCT2 OCT8  = s a )
 ( [ ‡ ∑ Ä ] OCT1 OCT2 OCT8  = v a )
 ( [ ‡ ∑ Å ] OCT1 OCT2 OCT8  = sha a )
 ( [ ‡ ∂ õ ] OCT1 OCT2 OCT8  = k a )
 ( [ ‡ ∂ ö ] OCT1 OCT2 OCT8  = k a )
 ( [ ‡ ∂ ù ] OCT1 OCT2 OCT8  = g a )
 ( [ ‡ ∂ ú ] OCT1 OCT2 OCT8  = g a )
 ( [ ‡ ∂ ü ] OCT1 OCT2 OCT8  = sg a )
 ( [ ‡ ∂ û ] OCT1 OCT2 OCT8  = on a )
 ( [ ‡ ∂ ° ] OCT1 OCT2 OCT8  = cha a )
 ( [ ‡ ∂ † ] OCT1 OCT2 OCT8  = cha a )
 ( [ ‡ ∂ £ ] OCT1 OCT2 OCT8  = j a )
 ( [ ‡ ∂ ¢ ] OCT1 OCT2 OCT8  = j a )
 ( [ ‡ ∂ • ] OCT1 OCT2 OCT8  = j nga a )
 ( [ ‡ ∂ § ] OCT1 OCT2 OCT8  = nga a )
 ( [ ‡ ∂ ß ] OCT1 OCT2 OCT8  = t a )
 ( [ ‡ ∂ ¶ ] OCT1 OCT2 OCT8  = j a )
 ( [ ‡ ∂ © ] OCT1 OCT2 OCT8  = d a )
 ( [ ‡ ∂ ® ] OCT1 OCT2 OCT8  = t a )
 ( [ ‡ ∂ ´ ] OCT1 OCT2 OCT8  = n a )
 ( [ ‡ ∂ ™ ] OCT1 OCT2 OCT8  = d a )
 ( [ ‡ ∂ ≠ ] OCT1 OCT2 OCT8  = tha a )
 ( [ ‡ ∂ ¨ ] OCT1 OCT2 OCT8  = sd a )
 ( [ ‡ ∂ Ø ] OCT1 OCT2 OCT8  = dha a )
 ( [ ‡ ∂ Æ ] OCT1 OCT2 OCT8  = tha a )
 ( [ ‡ ∂ ± ] OCT1 OCT2 OCT8  = n a )
 ( [ ‡ ∂ ∞ ] OCT1 OCT2 OCT8  = dha a )
 ( [ ‡ ∂ ≥ ] OCT1 OCT2 OCT8  = sdha a )
 ( [ ‡ ∂ µ ] OCT1 OCT2 OCT8  = p a )
 ( [ ‡ ∂ ¥ ] OCT1 OCT2 OCT8  = p a )
 ( [ ‡ ∂ ∑ ] OCT1 OCT2 OCT8  = b a )
 ( [ ‡ ∂ ∂ ] OCT1 OCT2 OCT8  = b a )
 ( [ ‡ ∂ π ] OCT1 OCT2 OCT8  = sba a )
 ( [ ‡ ∂ ∏ ] OCT1 OCT2 OCT8  = m a )
 ( [ ‡ ∂ ª ] OCT1 OCT2 OCT8  = r a )
 ( [ ‡ ∂ ∫ ] OCT1 OCT2 OCT8  = y a )
 ( [ ‡ ∂ Ω ] OCT1 OCT2 OCT8  = l a )
 ;;lankava}
 
 ( # [ ‡ ∑ Ü ] OCT1 OCT2 OCT3 = f a )
 ( # [ ‡ ∑ Ñ ] OCT1 OCT2 OCT3 = h a )
 ( # [ ‡ ∑ Ö ] OCT1 OCT2 OCT3 = l a )
 ( # [ ‡ ∑ Ç ] OCT1 OCT2 OCT3 = sha a )
 ( # [ ‡ ∑ É ] OCT1 OCT2 OCT3 = s a )
 ( # [ ‡ ∑ Ä ] OCT1 OCT2 OCT3 = v a )
 ( # [ ‡ ∑ Å ] OCT1 OCT2 OCT3 = sha a )
 ( # [ ‡ ∂ õ ] OCT1 OCT2 OCT3 = k a )
 ( # [ ‡ ∂ ö ] OCT1 OCT2 OCT3 = k a )
 ( # [ ‡ ∂ ù ] OCT1 OCT2 OCT3 = g a )
 ( # [ ‡ ∂ ú ] OCT1 OCT2 OCT3 = g a )
 ( # [ ‡ ∂ ü ] OCT1 OCT2 OCT3 = sg a )
 ( # [ ‡ ∂ û ] OCT1 OCT2 OCT3 = on a )
 ( # [ ‡ ∂ ° ] OCT1 OCT2 OCT3 = cha a )
 ( # [ ‡ ∂ † ] OCT1 OCT2 OCT3 = cha a )
 ( # [ ‡ ∂ £ ] OCT1 OCT2 OCT3 = j a )
 ( # [ ‡ ∂ ¢ ] OCT1 OCT2 OCT3 = j a )
 ( # [ ‡ ∂ • ] OCT1 OCT2 OCT3 = j nga a )
 ( # [ ‡ ∂ § ] OCT1 OCT2 OCT3 = nga a )
 ( # [ ‡ ∂ ß ] OCT1 OCT2 OCT3 = t a )
 ( # [ ‡ ∂ ¶ ] OCT1 OCT2 OCT3 = j a )
 ( # [ ‡ ∂ © ] OCT1 OCT2 OCT3 = d a )
 ( # [ ‡ ∂ ® ] OCT1 OCT2 OCT3 = t a )
 ( # [ ‡ ∂ ´ ] OCT1 OCT2 OCT3 = n a )
 ( # [ ‡ ∂ ™ ] OCT1 OCT2 OCT3 = d a )
 ( # [ ‡ ∂ ≠ ] OCT1 OCT2 OCT3 = tha a )
 ( # [ ‡ ∂ ¨ ] OCT1 OCT2 OCT3 = sd a )
 ( # [ ‡ ∂ Ø ] OCT1 OCT2 OCT3 = dha a )
 ( # [ ‡ ∂ Æ ] OCT1 OCT2 OCT3 = tha a )
 ( # [ ‡ ∂ ± ] OCT1 OCT2 OCT3 = n a )
 ( # [ ‡ ∂ ∞ ] OCT1 OCT2 OCT3 = dha a )
 ( # [ ‡ ∂ ≥ ] OCT1 OCT2 OCT3 = sdha a )
 ( # [ ‡ ∂ µ ] OCT1 OCT2 OCT3 = p a )
 ( # [ ‡ ∂ ¥ ] OCT1 OCT2 OCT3 = p a )
 ( # [ ‡ ∂ ∑ ] OCT1 OCT2 OCT3 = b a )
 ( # [ ‡ ∂ ∂ ] OCT1 OCT2 OCT3 = b a )
 ( # [ ‡ ∂ π ] OCT1 OCT2 OCT3 = sba a )
 ( # [ ‡ ∂ ∏ ] OCT1 OCT2 OCT3 = m a )
 ( # [ ‡ ∂ ª ] OCT1 OCT2 OCT3 = r a )
 ( # [ ‡ ∂ ∫ ] OCT1 OCT2 OCT3 = y a )
 ( # [ ‡ ∂ Ω ] OCT1 OCT2 OCT3 = l a )
 
 ( # [ ‡ ∑ Ü ] OCT1 OCT4 OCT6 = f a )
 ( # [ ‡ ∑ Ñ ] OCT1 OCT4 OCT6 = h a )
 ( # [ ‡ ∑ Ö ] OCT1 OCT4 OCT6 = l a )
 ( # [ ‡ ∑ Ç ] OCT1 OCT4 OCT6 = sha a )
 ( # [ ‡ ∑ É ] OCT1 OCT4 OCT6 = s a )
 ( # [ ‡ ∑ Ä ] OCT1 OCT4 OCT6 = v a )
 ( # [ ‡ ∑ Å ] OCT1 OCT4 OCT6 = sha a )
 ( # [ ‡ ∂ õ ] OCT1 OCT4 OCT6 = k a )
 ( # [ ‡ ∂ ö ] OCT1 OCT4 OCT6 = k a )
 ( # [ ‡ ∂ ù ] OCT1 OCT4 OCT6 = g a )
 ( # [ ‡ ∂ ú ] OCT1 OCT4 OCT6 = g a )
 ( # [ ‡ ∂ ü ] OCT1 OCT4 OCT6 = sg a )
 ( # [ ‡ ∂ û ] OCT1 OCT4 OCT6 = on a )
 ( # [ ‡ ∂ ° ] OCT1 OCT4 OCT6 = cha a )
 ( # [ ‡ ∂ † ] OCT1 OCT4 OCT6 = cha a )
 ( # [ ‡ ∂ £ ] OCT1 OCT4 OCT6 = j a )
 ( # [ ‡ ∂ ¢ ] OCT1 OCT4 OCT6 = j a )
 ( # [ ‡ ∂ • ] OCT1 OCT4 OCT6 = j nga a )
 ( # [ ‡ ∂ § ] OCT1 OCT4 OCT6 = nga a )
 ( # [ ‡ ∂ ß ] OCT1 OCT4 OCT6 = t a )
 ( # [ ‡ ∂ ¶ ] OCT1 OCT4 OCT6 = j a )
 ( # [ ‡ ∂ © ] OCT1 OCT4 OCT6 = d a )
 ( # [ ‡ ∂ ® ] OCT1 OCT4 OCT6 = t a )
 ( # [ ‡ ∂ ´ ] OCT1 OCT4 OCT6 = n a )
 ( # [ ‡ ∂ ™ ] OCT1 OCT4 OCT6 = d a )
 ( # [ ‡ ∂ ≠ ] OCT1 OCT4 OCT6 = tha a )
 ( # [ ‡ ∂ ¨ ] OCT1 OCT4 OCT6 = sd a )
 ( # [ ‡ ∂ Ø ] OCT1 OCT4 OCT6 = dha a )
 ( # [ ‡ ∂ Æ ] OCT1 OCT4 OCT6 = tha a )
 ( # [ ‡ ∂ ± ] OCT1 OCT4 OCT6 = n a )
 ( # [ ‡ ∂ ∞ ] OCT1 OCT4 OCT6 = dha a )
 ( # [ ‡ ∂ ≥ ] OCT1 OCT4 OCT6 = sdha a )
 ( # [ ‡ ∂ µ ] OCT1 OCT4 OCT6 = p a )
 ( # [ ‡ ∂ ¥ ] OCT1 OCT4 OCT6 = p a )
 ( # [ ‡ ∂ ∑ ] OCT1 OCT4 OCT6 = b a )
 ( # [ ‡ ∂ ∂ ] OCT1 OCT4 OCT6 = b a )
 ( # [ ‡ ∂ π ] OCT1 OCT4 OCT6 = sba a )
 ( # [ ‡ ∂ ∏ ] OCT1 OCT4 OCT6 = m a )
 ( # [ ‡ ∂ ª ] OCT1 OCT4 OCT6 = r a )
 ( # [ ‡ ∂ ∫ ] OCT1 OCT4 OCT6 = y a )
 ( # [ ‡ ∂ Ω ] OCT1 OCT4 OCT6 = l a )
 
 ( [ ‡ ∑ Ü ] OCT1 OCT2 OCT3 = f aaa )
 ( [ ‡ ∑ Ñ ] OCT1 OCT2 OCT3 = h aaa )
 ( [ ‡ ∑ Ö ] OCT1 OCT2 OCT3 = l aaa )
 ( [ ‡ ∑ Ç ] OCT1 OCT2 OCT3 = sha aaa )
 ( [ ‡ ∑ É ] OCT1 OCT2 OCT3 = s aaa )
 ( [ ‡ ∑ Ä ] OCT1 OCT2 OCT3 = v aaa )
 ( [ ‡ ∑ Å ] OCT1 OCT2 OCT3 = sha aaa )
 ( [ ‡ ∂ õ ] OCT1 OCT2 OCT3 = k aaa )
 ( [ ‡ ∂ ö ] OCT1 OCT2 OCT3 = k aaa )
 ( [ ‡ ∂ ù ] OCT1 OCT2 OCT3 = g aaa )
 ( [ ‡ ∂ ú ] OCT1 OCT2 OCT3 = g aaa )
 ( [ ‡ ∂ ü ] OCT1 OCT2 OCT3 = sg aaa )
 ( [ ‡ ∂ û ] OCT1 OCT2 OCT3 = on aaa )
 ( [ ‡ ∂ ° ] OCT1 OCT2 OCT3 = cha aaa )
 ( [ ‡ ∂ † ] OCT1 OCT2 OCT3 = cha aaa )
 ( [ ‡ ∂ £ ] OCT1 OCT2 OCT3 = j aaa )
 ( [ ‡ ∂ ¢ ] OCT1 OCT2 OCT3 = j aaa )
 ( [ ‡ ∂ • ] OCT1 OCT2 OCT3 = j nga aaa )
 ( [ ‡ ∂ § ] OCT1 OCT2 OCT3 = nga aaa )
 ( [ ‡ ∂ ß ] OCT1 OCT2 OCT3 = t aaa )
 ( [ ‡ ∂ ¶ ] OCT1 OCT2 OCT3 = j aaa )
 ( [ ‡ ∂ © ] OCT1 OCT2 OCT3 = d aaa )
 ( [ ‡ ∂ ® ] OCT1 OCT2 OCT3 = t aaa )
 ( [ ‡ ∂ ´ ] OCT1 OCT2 OCT3 = n aaa )
 ( [ ‡ ∂ ™ ] OCT1 OCT2 OCT3 = d aaa )
 ( [ ‡ ∂ ≠ ] OCT1 OCT2 OCT3 = tha aaa )
 ( [ ‡ ∂ ¨ ] OCT1 OCT2 OCT3 = sd aaa )
 ( [ ‡ ∂ Ø ] OCT1 OCT2 OCT3 = dha aaa )
 ( [ ‡ ∂ Æ ] OCT1 OCT2 OCT3 = tha aaa )
 ( [ ‡ ∂ ± ] OCT1 OCT2 OCT3 = n aaa )
 ( [ ‡ ∂ ∞ ] OCT1 OCT2 OCT3 = dha aaa )
 ( [ ‡ ∂ ≥ ] OCT1 OCT2 OCT3 = sdha aaa )
 ( [ ‡ ∂ µ ] OCT1 OCT2 OCT3 = p aaa )
 ( [ ‡ ∂ ¥ ] OCT1 OCT2 OCT3 = p aaa )
 ( [ ‡ ∂ ∑ ] OCT1 OCT2 OCT3 = b aaa )
 ( [ ‡ ∂ ∂ ] OCT1 OCT2 OCT3 = b aaa )
 ( [ ‡ ∂ π ] OCT1 OCT2 OCT3 = sba aaa )
 ( [ ‡ ∂ ∏ ] OCT1 OCT2 OCT3 = m aaa )
 ( [ ‡ ∂ ª ] OCT1 OCT2 OCT3 = r aaa )
 ( [ ‡ ∂ ∫ ] OCT1 OCT2 OCT3 = y aaa )
 ( [ ‡ ∂ Ω ] OCT1 OCT2 OCT3 = l aaa )
 
 ( [ ‡ ∑ Ü ] OCT1 OCT4 OCT6 = f aaa )
 ( [ ‡ ∑ Ñ ] OCT1 OCT4 OCT6 = h aaa )
 ( [ ‡ ∑ Ö ] OCT1 OCT4 OCT6 = l aaa )
 ( [ ‡ ∑ Ç ] OCT1 OCT4 OCT6 = sha aaa )
 ( [ ‡ ∑ É ] OCT1 OCT4 OCT6 = s aaa )
 ( [ ‡ ∑ Ä ] OCT1 OCT4 OCT6 = v aaa )
 ( [ ‡ ∑ Å ] OCT1 OCT4 OCT6 = sha aaa )
 ( [ ‡ ∂ õ ] OCT1 OCT4 OCT6 = k aaa )
 ( [ ‡ ∂ ö ] OCT1 OCT4 OCT6 = k aaa )
 ( [ ‡ ∂ ù ] OCT1 OCT4 OCT6 = g aaa )
 ( [ ‡ ∂ ú ] OCT1 OCT4 OCT6 = g aaa )
 ( [ ‡ ∂ ü ] OCT1 OCT4 OCT6 = sg aaa )
 ( [ ‡ ∂ û ] OCT1 OCT4 OCT6 = on aaa )
 ( [ ‡ ∂ ° ] OCT1 OCT4 OCT6 = cha aaa )
 ( [ ‡ ∂ † ] OCT1 OCT4 OCT6 = cha aaa )
 ( [ ‡ ∂ £ ] OCT1 OCT4 OCT6 = j aaa )
 ( [ ‡ ∂ ¢ ] OCT1 OCT4 OCT6 = j aaa )
 ( [ ‡ ∂ • ] OCT1 OCT4 OCT6 = j nga aaa )
 ( [ ‡ ∂ § ] OCT1 OCT4 OCT6 = nga aaa )
 ( [ ‡ ∂ ß ] OCT1 OCT4 OCT6 = t aaa )
 ( [ ‡ ∂ ¶ ] OCT1 OCT4 OCT6 = j aaa )
 ( [ ‡ ∂ © ] OCT1 OCT4 OCT6 = d aaa )
 ( [ ‡ ∂ ® ] OCT1 OCT4 OCT6 = t aaa )
 ( [ ‡ ∂ ´ ] OCT1 OCT4 OCT6 = n aaa )
 ( [ ‡ ∂ ™ ] OCT1 OCT4 OCT6 = d aaa )
 ( [ ‡ ∂ ≠ ] OCT1 OCT4 OCT6 = tha aaa )
 ( [ ‡ ∂ ¨ ] OCT1 OCT4 OCT6 = sd aaa )
 ( [ ‡ ∂ Ø ] OCT1 OCT4 OCT6 = dha aaa )
 ( [ ‡ ∂ Æ ] OCT1 OCT4 OCT6 = tha aaa )
 ( [ ‡ ∂ ± ] OCT1 OCT4 OCT6 = n aaa )
 ( [ ‡ ∂ ∞ ] OCT1 OCT4 OCT6 = dha aaa )
 ( [ ‡ ∂ ≥ ] OCT1 OCT4 OCT6 = sdha aaa )
 ( [ ‡ ∂ µ ] OCT1 OCT4 OCT6 = p aaa )
 ( [ ‡ ∂ ¥ ] OCT1 OCT4 OCT6 = p aaa )
 ( [ ‡ ∂ ∑ ] OCT1 OCT4 OCT6 = b aaa )
 ( [ ‡ ∂ ∂ ] OCT1 OCT4 OCT6 = b aaa )
 ( [ ‡ ∂ π ] OCT1 OCT4 OCT6 = sba aaa )
 ( [ ‡ ∂ ∏ ] OCT1 OCT4 OCT6 = m aaa )
 ( [ ‡ ∂ ª ] OCT1 OCT4 OCT6 = r aaa )
 ( [ ‡ ∂ ∫ ] OCT1 OCT4 OCT6 = y aaa )
 ( [ ‡ ∂ Ω ] OCT1 OCT4 OCT6 = l aaa )
 
 
 ( [ ‡ ∑ Ü ] ‡ ∑ ä # = f )
 ( [ ‡ ∑ Ñ ] ‡ ∑ ä # = h )
 ( [ ‡ ∑ Ö ] ‡ ∑ ä # = l )
 ( [ ‡ ∑ Ç ] ‡ ∑ ä # = sha )
 ( [ ‡ ∑ É ] ‡ ∑ ä # = s )
 ( [ ‡ ∑ Ä ] ‡ ∑ ä # = v )
 ( [ ‡ ∑ Å ] ‡ ∑ ä # = sha )
 ( [ ‡ ∂ õ ] ‡ ∑ ä # = k )
 ( [ ‡ ∂ ö ] ‡ ∑ ä # = k )
 ( [ ‡ ∂ ù ] ‡ ∑ ä # = g )
 ( [ ‡ ∂ ú ] ‡ ∑ ä # = g )
 ( [ ‡ ∂ ü ] ‡ ∑ ä # = sg )
 ( [ ‡ ∂ û ] ‡ ∑ ä # = on )
 ( [ ‡ ∂ ° ] ‡ ∑ ä # = cha )
 ( [ ‡ ∂ † ] ‡ ∑ ä # = cha )
 ( [ ‡ ∂ £ ] ‡ ∑ ä # = j )
 ( [ ‡ ∂ ¢ ] ‡ ∑ ä # = j )
 ( [ ‡ ∂ • ] ‡ ∑ ä # = j nga )
 ( [ ‡ ∂ § ] ‡ ∑ ä # = nga )
 ( [ ‡ ∂ ß ] ‡ ∑ ä # = t )
 ( [ ‡ ∂ ¶ ] ‡ ∑ ä # = j )
 ( [ ‡ ∂ © ] ‡ ∑ ä # = d )
 ( [ ‡ ∂ ® ] ‡ ∑ ä # = t )
 ( [ ‡ ∂ ´ ] ‡ ∑ ä # = n )
 ( [ ‡ ∂ ™ ] ‡ ∑ ä # = d )
 ( [ ‡ ∂ ≠ ] ‡ ∑ ä # = tha )
 ( [ ‡ ∂ ¨ ] ‡ ∑ ä # = sd )
 ( [ ‡ ∂ Ø ] ‡ ∑ ä # = dha )
 ( [ ‡ ∂ Æ ] ‡ ∑ ä # = tha )
 ( [ ‡ ∂ ± ] ‡ ∑ ä # = n )
 ( [ ‡ ∂ ∞ ] ‡ ∑ ä # = dha )
 ( [ ‡ ∂ ≥ ] ‡ ∑ ä # = sdha )
 ( [ ‡ ∂ µ ] ‡ ∑ ä # = p )
 ( [ ‡ ∂ ¥ ] ‡ ∑ ä # = p )
 ( [ ‡ ∂ ∑ ] ‡ ∑ ä # = b )
 ( [ ‡ ∂ ∂ ] ‡ ∑ ä # = b )
 ( [ ‡ ∂ π ] ‡ ∑ ä # = sba )
 ( [ ‡ ∂ ∏ ] ‡ ∑ ä # = m )
 ( [ ‡ ∂ ª ] ‡ ∑ ä # = r )
 ( [ ‡ ∂ ∫ ] ‡ ∑ ä # = y )
 ( [ ‡ ∂ Ω ] ‡ ∑ ä # = l )

 ( [ ‡ ∑ Ü ]  ‡ ∑ ä # = f )
 ( [ ‡ ∑ Ñ ]  ‡ ∑ ä # = h )
 ( [ ‡ ∑ Ö ]  ‡ ∑ ä # = l )
 ( [ ‡ ∑ Ç ]  ‡ ∑ ä # = sha )
 ( [ ‡ ∑ É ]  ‡ ∑ ä # = s )
 ( [ ‡ ∑ Ä ]  ‡ ∑ ä # = v )
 ( [ ‡ ∑ Å ]  ‡ ∑ ä # = sha )
 ( [ ‡ ∂ õ ]  ‡ ∑ ä # = k )
 ( [ ‡ ∂ ö ]  ‡ ∑ ä # = k )
 ( [ ‡ ∂ ù ]  ‡ ∑ ä # = g )
 ( [ ‡ ∂ ú ]  ‡ ∑ ä # = g )
 ( [ ‡ ∂ ü ]  ‡ ∑ ä # = sg )
 ( [ ‡ ∂ û ]  ‡ ∑ ä # = on )
 ( [ ‡ ∂ ° ]  ‡ ∑ ä # = cha )
 ( [ ‡ ∂ † ]  ‡ ∑ ä # = cha )
 ( [ ‡ ∂ £ ]  ‡ ∑ ä # = j )
 ( [ ‡ ∂ ¢ ]  ‡ ∑ ä # = j )
 ( [ ‡ ∂ • ]  ‡ ∑ ä # = j nga )
 ( [ ‡ ∂ § ]  ‡ ∑ ä # = nga )
 ( [ ‡ ∂ ß ]  ‡ ∑ ä # = t )
 ( [ ‡ ∂ ¶ ]  ‡ ∑ ä # = j )
 ( [ ‡ ∂ © ]  ‡ ∑ ä # = d )
 ( [ ‡ ∂ ® ]  ‡ ∑ ä # = t )
 ( [ ‡ ∂ ´ ]  ‡ ∑ ä # = n )
 ( [ ‡ ∂ ™ ]  ‡ ∑ ä # = d )
 ( [ ‡ ∂ ≠ ]  ‡ ∑ ä # = tha )
 ( [ ‡ ∂ ¨ ]  ‡ ∑ ä # = sd )
 ( [ ‡ ∂ Ø ]  ‡ ∑ ä # = dha )
 ( [ ‡ ∂ Æ ]  ‡ ∑ ä # = tha )
 ( [ ‡ ∂ ± ]  ‡ ∑ ä # = n )
 ( [ ‡ ∂ ∞ ]  ‡ ∑ ä # = dha )
 ( [ ‡ ∂ ≥ ]  ‡ ∑ ä # = sdha )
 ( [ ‡ ∂ µ ]  ‡ ∑ ä # = p )
 ( [ ‡ ∂ ¥ ]  ‡ ∑ ä # = p )
 ( [ ‡ ∂ ∑ ]  ‡ ∑ ä # = b )
 ( [ ‡ ∂ ∂ ]  ‡ ∑ ä # = b )
 ( [ ‡ ∂ π ]  ‡ ∑ ä # = sba )
 ( [ ‡ ∂ ∏ ]  ‡ ∑ ä # = m )
 ( [ ‡ ∂ ª ]  ‡ ∑ ä # = r )
 ( [ ‡ ∂ ∫ ]  ‡ ∑ ä # = y )
 ( [ ‡ ∂ Ω ]  ‡ ∑ ä # = l )
 
 ( [ ‡ ∑ Ü ] # = f aaa )
 ( [ ‡ ∑ Ñ ] # = h aaa )
 ( [ ‡ ∑ Ö ] # = l aaa )
 ( [ ‡ ∑ Ç ] # = sha aaa )
 ( [ ‡ ∑ É ] # = s aaa )
 ( [ ‡ ∑ Ä ] # = v aaa )
 ( [ ‡ ∑ Å ] # = sha aaa )
 ( [ ‡ ∂ õ ] # = k aaa )
 ( [ ‡ ∂ ö ] # = k aaa )
 ( [ ‡ ∂ ù ] # = g aaa )
 ( [ ‡ ∂ ú ] # = g aaa )
 ( [ ‡ ∂ ü ] # = sg aaa )
 ( [ ‡ ∂ û ] # = on aaa )
 ( [ ‡ ∂ ° ] # = cha aaa )
 ( [ ‡ ∂ † ] # = cha aaa )
 ( [ ‡ ∂ £ ] # = j aaa )
 ( [ ‡ ∂ ¢ ] # = j aaa )
 ( [ ‡ ∂ • ] # = j nga aaa )
 ( [ ‡ ∂ § ] # = nga aaa )
 ( [ ‡ ∂ ß ] # = t aaa )
 ( [ ‡ ∂ ¶ ] # = j aaa )
 ( [ ‡ ∂ © ] # = d aaa )
 ( [ ‡ ∂ ® ] # = t aaa )
 ( [ ‡ ∂ ´ ] # = n aaa )
 ( [ ‡ ∂ ™ ] # = d aaa )
 ( [ ‡ ∂ ≠ ] # = tha aaa )
 ( [ ‡ ∂ ¨ ] # = sd aaa )
 ( [ ‡ ∂ Ø ] # = dha aaa )
 ( [ ‡ ∂ Æ ] # = tha aaa )
 ( [ ‡ ∂ ± ] # = n aaa )
 ( [ ‡ ∂ ∞ ] # = dha aaa )
 ( [ ‡ ∂ ≥ ] # = sdha aaa )
 ( [ ‡ ∂ µ ] # = p aaa )
 ( [ ‡ ∂ ¥ ] # = p aaa )
 ( [ ‡ ∂ ∑ ] # = b aaa )
 ( [ ‡ ∂ ∂ ] # = b aaa )
 ( [ ‡ ∂ π ] # = sba aaa )
 ( [ ‡ ∂ ∏ ] # = m aaa )
 ( [ ‡ ∂ ª ] # = r aaa )
 ( [ ‡ ∂ ∫ ] # = y aaa )
 ( [ ‡ ∂ Ω ] # = l aaa )
 
 ( [ ‡ ∑ Ü ] = f )
 ( [ ‡ ∑ Ñ ] = h )
 ( [ ‡ ∑ Ö ] = l )
 ( [ ‡ ∑ Ç ] = sha )
 ( [ ‡ ∑ É ] = s )
 ( [ ‡ ∑ Ä ] = v )
 ( [ ‡ ∑ Å ] = sha )
 ( [ ‡ ∂ õ ] = k )
 ( [ ‡ ∂ ö ] = k )
 ( [ ‡ ∂ ù ] = g )
 ( [ ‡ ∂ ú ] = g )
 ( [ ‡ ∂ ü ] = sg )
 ( [ ‡ ∂ û ] = on )
 ( [ ‡ ∂ ° ] = cha )
 ( [ ‡ ∂ † ] = cha )
 ( [ ‡ ∂ £ ] = j )
 ( [ ‡ ∂ ¢ ] = j )
 ( [ ‡ ∂ • ] = j nga )
 ( [ ‡ ∂ § ] = nga )
 ( [ ‡ ∂ ß ] = t )
 ( [ ‡ ∂ ¶ ] = j )
 ( [ ‡ ∂ © ] = d )
 ( [ ‡ ∂ ® ] = t )
 ( [ ‡ ∂ ´ ] = n )
 ( [ ‡ ∂ ™ ] = d )
 ( [ ‡ ∂ ≠ ] = tha )
 ( [ ‡ ∂ ¨ ] = sd )
 ( [ ‡ ∂ Ø ] = dha )
 ( [ ‡ ∂ Æ ] = tha )
 ( [ ‡ ∂ ± ] = n )
 ( [ ‡ ∂ ∞ ] = dha )
 ( [ ‡ ∂ ≥ ] = sdha )
 ( [ ‡ ∂ µ ] = p )
 ( [ ‡ ∂ ¥ ] = p )
 ( [ ‡ ∂ ∑ ] = b )
 ( [ ‡ ∂ ∂ ] = b )
 ( [ ‡ ∂ π ] = sba )
 ( [ ‡ ∂ ∏ ] = m )
 ( [ ‡ ∂ ª ] = r )
 ( [ ‡ ∂ ∫ ] = y )
 ( [ ‡ ∂ Ω ] = l )
 ( [ ‡ ∂ É ] = h )
 ( [ ‡ ∂ Ç ] = on )
 
 ( [ ‡ ∂ Ö ] = a )
 ( [ ‡ ∂ á ] = ae )
 ( [ ‡ ∂ Ü ] = aa aa )
 ( [ ‡ ∂ â ] = i )
 ( [ ‡ ∂ à ] = aee aee )
 ( [ ‡ ∂ ã ] = u )
 ( [ ‡ ∂ ä ] = ii ii )
 ( [ ‡ ∂ ç ] = r i )
 ( [ ‡ ∂ å ] = uu uu )
 ( [ ‡ ∂ è ] = i l u )
 ( [ ‡ ∂ é ] = r ii )
 ( [ ‡ ∂ ë ] = e )
 ( [ ‡ ∂ ê ] = i l uu )
 ( [ ‡ ∂ ì ] = a i )
 ( [ ‡ ∂ í ] = ee ee )
 ( [ ‡ ∂ ï ] = oo oo )
 ( [ ‡ ∂ î ] = o )
 ( [ ‡ ∂ ñ ] = a u )
 
 
 
 ( [ ‡ ∑ ä ] = ) ;hal lakuna
 ( [ ‚ Ä ç ] = ) ;zwj
 ( [ ‡ ∑ ¥ ] = ) ;kundaliya

 
 )
)
;;; Function called when word not found in lexicon
(define (ucsc_sin_lts_function word features)
 "(ucsc_sin_lts_function WORD FEATURES)
Return pronunciation of word not in lexicon."
 (let ((phones) (entry))
  (set! entry
  (if (lts.in.alphabet word 'sin_charset)
	(list
	 word
	 features
	 ;; Currently ignore syllabification
	;; (list (list (lts.apply word 'sin_charset) 1)))
	(syllabify (lts.apply word 'sin_charset)))
	(begin
	 (format stderr "unpronounciation word %s\n" word)
	 (list word features '(((m aa t aaa ee ee k aaa k i y aaa v aa n n aaa b ae h ae) 1))))))
;;  (format t "%l\n" entry)
  entry))

(define (ucsc_sin_addenda)
 "(ucsc_addenda)
Basic lexicon should (must ?) basic letters and punctuation."
;(lex.add.entry '("???" n (((ee) 0) ((t i) 0) ((a n d) 0) ((t i) 0))))
(lex.add.entry '("‡∂ö‡∂ª‡∂ß" n  (((k a) 0) ((r aaa) 0) ((t aaa) 0))))
(lex.add.entry '("space" n (((h i s) 0) ((tha ae) 0) ((n a k) 0))))
(lex.add.entry '("language" n (((b aa) 0) ((sha aa) 0) ((v aaa) 0))))
(lex.add.entry '("backspace" n (((aa) 0) ((p a) 0) ((s u) 0))))
(lex.add.entry '("emptyline" n ((( k ) 0))))

(lex.add.entry '("." punc nil))
(lex.add.entry '("'" punc nil))
(lex.add.entry '(":" punc nil))
(lex.add.entry '(";" punc nil))
(lex.add.entry '("," punc nil))
(lex.add.entry '("-" punc nil))
(lex.add.entry '("\"" punc nil))
(lex.add.entry '("`" punc nil))
(lex.add.entry '("?" punc nil))
(lex.add.entry '("!" punc nil))
)

;;; Lexicon definition

(lex.create "ucsc_sin_l")
(lex.set.phoneset "ucsc_sin_sdn")
(lex.set.lts.method 'ucsc_sin_lts_function)
(ucsc_sin_addenda)

(provide 'ucsc_sin_sdn_lex)
