#!/bin/sh
set -e

if ! grep '^[[:space:]]*MOZ_DISABLE_PANGO=' /etc/environment > /dev/null
then
	echo -n 'adding MOZ_DISABLE_PANGO=0 to /etc/environment ...'
	echo 'MOZ_DISABLE_PANGO=0' >> /etc/environment
	echo ' done'
fi

exit 0

