#!/bin/sh
set -e

if ! grep '^[[:space:]]*export[[:space:]][[:space:]]*MOZ_ENABLE_PANGO=' /etc/environment > /dev/null
then
	echo -n 'adding MOZ_ENABLE_PANGO to /etc/environment...'
	echo 'export MOZ_ENABLE_PANGO=1' >> /etc/environment
	echo ' done'
fi

exit 0

