#ifndef ALTKEY_DEF
#define ALTKEY_DEF(name,flags)
#endif

ALTKEY_DEF(NDAYANNA, CHTYPE_SIMPLE|CHTYPE____)
ALTKEY_DEF(DGAYANU,  CHTYPE_SIMPLE|CHTYPE__M_)	// modifier without a list
ALTKEY_DEF(VISARGA,  CHTYPE_SIMPLE|CHTYPE___C)
ALTKEY_DEF(NJAYANNA, CHTYPE_SIMPLE|CHTYPE____)
ALTKEY_DEF(NDDAYANNA,CHTYPE_SIMPLE|CHTYPE____)
ALTKEY_DEF(ILUYANNA, CHTYPE_SIMPLE|CHTYPE____)
ALTKEY_DEF(NGAYANNA, CHTYPE_SIMPLE|CHTYPE____)

#undef ALTKEY_DEF
