#ifndef MODLIST_DEF
#define MODLIST_DEF(name)
#endif

MODLIST_DEF(Al)
MODLIST_DEF(Aela)
MODLIST_DEF(Aeda)
MODLIST_DEF(DAeda)
MODLIST_DEF(Gaeta)
MODLIST_DEF(Kombu)
MODLIST_DEF(Gayanu)

#undef MODLIST_DEF
